openapi: 3.0.3
info:
  title: Microservicio de Gestión de Usuarios - ASEE
  version: 1.0.0
  description: API para gestión de usuarios

servers:
  - url: http://localhost:8080/api/v1

paths:
  /users:
    get:
      summary: Listar usuarios
      operationId: listUsers
      responses:
        '200':
          description: Lista de usuarios
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/User'
    post:
      summary: Crear usuario
      operationId: createUser
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserCreate'
      responses:
        '201':
          description: Usuario creado

  /users/{userId}:
    get:
      summary: Obtener usuario
      operationId: getUserById
      parameters:
        - name: userId
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Usuario encontrado
    put:
      summary: Actualizar usuario
      operationId: updateUser
      parameters:
        - name: userId
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserCreate'
      responses:
        '200':
          description: Usuario actualizado
    delete:
      summary: Eliminar usuario
      operationId: deleteUser
      parameters:
        - name: userId
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Usuario eliminado

components:
  schemas:
    User:
      type: object
      properties:
        id:
          type: string
        username:
          type: string
        email:
          type: string
        fullName:
          type: string
        createdAt:
          type: string
          format: date-time
    
    UserCreate:
      type: object
      required:
        - username
        - email
        - fullName
      properties:
        username:
          type: string
        email:
          type: string
          format: email
        fullName:
          type: string